[Config]
# Redis健康检查定时器，单位秒
RedisHealthCheckTimer = 2
# 开启心跳
HeartBeat = false
#超过该时间未收到数据，认为网络断开
HBTimer = 10 
# 心跳包发送间隔
HBTicker = 4

# 开发调试模式(服务器panic错误会发往客户端)
Debug = 1

[Log]
# 日志文件存放的文件夹
LogDir = "../log/"
# 日志文件名为空则用可执行文件名
LogFileName = ""
# 日志配置文件
LogConfig = "../res/config/logConfig.xml"


#底层App用到的配置
[ServerApp]
ListenAddr = ":17010"
OuterIP = "127.0.0.1"
SvrMaxConn = 10000
IsEncrypt = false
#加载的服务, 服务名与下面的标签必须一致
Services = "serviceA"


#第一个定义是起"网关"作用的service,底层会用到这个"网关"服务名
[serviceA]
#:号之前不需要填，默认监听即可
SvrListenAddr = ":17000"
#外网ip,根据实际生产情况填写
OuterIP="127.0.0.1"
SvrMaxConn = 10000
# TickInterval 单位毫秒
TickInterval = 1000 
EntityMultiThread = true


[DB]
Addr = "127.0.0.1:6379"
MaxIdle = 50
IdleTimeout = 10
MaxActive = 500
Password = ""
Index = 1

[RedisForServer]
Addr = "127.0.0.1:6379"
MaxIdle = 50
IdleTimeout = 10
MaxActive = 500
Password = ""
Index = 0


[MongoDB]
GameDBName = "game"
Addr = "mongodb://game:123456@192.168.133.33:27017/game"
#Addr = "mongodb://mail:Zwp0K4h4zAjZQwkzdOH6fWIdPA6xieXmQpps@211.159.201.75:27017,211.159.201.76:27017/testM"
#Addr = "mongodb://127.0.0.1:27017"
Timeout = 5